database:
  host: "senior-project.cqpzjknbrdd2.us-west-2.rds.amazonaws.com"
  user: "root"
  password: "TBUASv565GdfPByVKdx2"
  database_name: "SJSU"

database_tables:
  personnels: "PERSONNELS"
  audit:
    database: "AUDIT_DATABASE"
    access_history: "AUDIT_ACCESS"