SHOW TABLES from SJSU;
DESCRIBE SJSU.PERSONNELS;
SELECT * FROM SJSU.PERSONNELS;
SELECT * from SJSU.PERSONNELS WHERE EMAIL = 'ryannguyen10292' AND PASSWORD = 'Test123';
SELECT ROLES FROM SJSU.PERSONNELS WHERE ID = 1;
SELECT ID, ROLES from SJSU.PERSONNELS WHERE EMAIL = 'ryannguyen10292' AND PASSWORD = 'Test123';
SELECT COUNT(*) from SJSU.PERSONNELS